<?php

namespace MrPrompt\Cielo\Enum\Localizacao;

use MrPrompt\Cielo\Exceptions\ValidacaoErrors;

enum Pais: string
{
    case AFEGANISTAO = 'AFG';
    case ALBANIA = 'ALB';
    case ARGELIA = 'DZA';
    case ANDORRA = 'AND';
    case ANGOLA = 'AGO';
    case ANTIGUA_E_BARBUDA = 'ATG';
    case ARGENTINA = 'ARG';
    case ARMENIA = 'ARM';
    case AUSTRALIA = 'AUS';
    case AUSTRIA = 'AUT';
    case AZERBAIJAO = 'AZE';
    case BAHAMAS = 'BHS';
    case BAREIN = 'BHR';
    case BANGLADESH = 'BGD';
    case BARBADOS = 'BRB';
    case BELARUS = 'BLR';
    case BELGICA = 'BEL';
    case BELIZE = 'BLZ';
    case BENIM = 'BEN';
    case BUTAO = 'BTN';
    case BOLIVIA = 'BOL';
    case BOSNIA_E_HERZEGOVINA = 'BIH';
    case BOTSUANA = 'BWA';
    case BRASIL = 'BRA';
    case BRUNEI = 'BRN';
    case BULGARIA = 'BGR';
    case BURKINA_FASO = 'BFA';
    case BURUNDI = 'BDI';
    case CABO_VERDE = 'CPV';
    case CAMBOJA = 'KHM';
    case CAMAROES = 'CMR';
    case CANADA = 'CAN';
    case REPUBLICA_CENTRO_AFRICANA = 'CAF';
    case CHADE = 'TCD';
    case CHILE = 'CHL';
    case CHINA = 'CHN';
    case COLOMBIA = 'COL';
    case COMORES = 'COM';
    case CONGO = 'COG';
    case COSTA_RICA = 'CRI';
    case CROACIA = 'HRV';
    case CUBA = 'CUB';
    case CHIPRE = 'CYP';
    case REPUBLICA_CHECA = 'CZE';
    case DINAMARCA = 'DNK';
    case DJIBUTI = 'DJI';
    case DOMINICA = 'DMA';
    case REPUBLICA_DOMINICANA = 'DOM';
    case EQUADOR = 'ECU';
    case EGITO = 'EGY';
    case EL_SALVADOR = 'SLV';
    case GUINE_EQUATORIAL = 'GNQ';
    case ERITREIA = 'ERI';
    case ESTONIA = 'EST';
    case ESUATINI = 'SWZ';
    case ETIOPIA = 'ETH';
    case FIJI = 'FJI';
    case FINLANDIA = 'FIN';
    case FRANCA = 'FRA';
    case GABAO = 'GAB';
    case GAMBIA = 'GMB';
    case GEORGIA = 'GEO';
    case ALEMANHA = 'DEU';
    case GANA = 'GHA';
    case GRECIA = 'GRC';
    case GRANADA = 'GRD';
    case GUATEMALA = 'GTM';
    case GUINE = 'GIN';
    case GUINE_BISSAU = 'GNB';
    case GUIANA = 'GUY';
    case HAITI = 'HTI';
    case HONDURAS = 'HND';
    case HUNGRIA = 'HUN';
    case ISLANDIA = 'ISL';
    case INDIA = 'IND';
    case INDONESIA = 'IDN';
    case IRA = 'IRN';
    case IRAQUE = 'IRQ';
    case IRLANDA = 'IRL';
    case ISRAEL = 'ISR';
    case ITALIA = 'ITA';
    case JAMAICA = 'JAM';
    case JAPAO = 'JPN';
    case JORDANIA = 'JOR';
    case CASAQUISTAO = 'KAZ';
    case QUENIA = 'KEN';
    case QUIRIBATI = 'KIR';
    case COREIA_DO_NORTE = 'PRK';
    case COREIA_DO_SUL = 'KOR';
    case KOSOVO = 'XKX';
    case KUWAIT = 'KWT';
    case QUIRGUIZISTAO = 'KGZ';
    case LAOS = 'LAO';
    case LETONIA = 'LVA';
    case LIBANO = 'LBN';
    case LESOTO = 'LSO';
    case LIBERIA = 'LBR';
    case LIBIA = 'LBY';
    case LIECHTENSTEIN = 'LIE';
    case LITUANIA = 'LTU';
    case LUXEMBURGO = 'LUX';
    case MADAGASCAR = 'MDG';
    case MALAWI = 'MWI';
    case MALASIA = 'MYS';
    case MALDIVAS = 'MDV';
    case MALI = 'MLI';
    case MALTA = 'MLT';
    case ILHAS_MARSHALL = 'MHL';
    case MAURITANIA = 'MRT';
    case MAURICIO = 'MUS';
    case MEXICO = 'MEX';
    case MICRONESIA = 'FSM';
    case MOLDAVIA = 'MDA';
    case MONACO = 'MCO';
    case MONGOLIA = 'MNG';
    case MONTENEGRO = 'MNE';
    case MARROCOS = 'MAR';
    case MOCAMBIQUE = 'MOZ';
    case MIANMAR = 'MMR';
    case NAMIBIA = 'NAM';
    case NAURU = 'NRU';
    case NEPAL = 'NPL';
    case PAISES_BAIXOS = 'NLD';
    case NOVA_ZELANDIA = 'NZL';
    case NICARAGUA = 'NIC';
    case NIGER = 'NER';
    case NIGERIA = 'NGA';
    case MACEDONIA_DO_NORTE = 'MKD';
    case NORUEGA = 'NOR';
    case OMA = 'OMN';
    case PAQUISTAO = 'PAK';
    case PALAU = 'PLW';
    case PALESTINA = 'PSE';
    case PANAMA = 'PAN';
    case PAPUA_NOVA_GUINE = 'PNG';
    case PARAGUAI = 'PRY';
    case PERU = 'PER';
    case FILIPINAS = 'PHL';
    case POLONIA = 'POL';
    case PORTUGAL = 'PRT';
    case CATAR = 'QAT';
    case RUMENIA = 'ROU';
    case RUSSIA = 'RUS';
    case RUANDA = 'RWA';
    case SAO_CRISTOVAO_E_NEVES = 'KNA';
    case SANTA_LUCIA = 'LCA';
    case SAO_VICENTE_E_GRANADINAS = 'VCT';
    case SAMOA = 'WSM';
    case SAN_MARINO = 'SMR';
    case SAO_TOME_E_PRINCIPE = 'STP';
    case ARABIA_SAUDITA = 'SAU';
    case SENEGAL = 'SEN';
    case SERVIA = 'SRB';
    case SEICHELES = 'SYC';
    case SERRA_LEOA = 'SLE';
    case CINGAPURA = 'SGP';
    case ESLOVAQUIA = 'SVK';
    case ESLOVENIA = 'SVN';
    case ILHAS_SALOMAO = 'SLB';
    case SOMALIA = 'SOM';
    case AFRICA_DO_SUL = 'ZAF';
    case SUDÃO_DO_SUL = 'SSD';
    case ESPANHA = 'ESP';
    case SRI_LANKA = 'LKA';
    case SUDÃO = 'SDN';
    case SURINAME = 'SUR';
    case SUECIA = 'SWE';
    case SUICA = 'CHE';
    case SIRIA = 'SYR';
    case TAIWAN = 'TWN';
    case TAJIQUISTAO = 'TJK';
    case TANZANIA = 'TZA';
    case TAILANDIA = 'THA';
    case TIMOR_LESTE = 'TLS';
    case TOGO = 'TGO';
    case TONGA = 'TON';
    case TRINDADE_E_TOBAGO = 'TTO';
    case TUNISIA = 'TUN';
    case TURQUIA = 'TUR';
    case TURQUEMENISTAO = 'TKM';
    case TUVALU = 'TUV';
    case UGANDA = 'UGA';
    case UCRANIA = 'UKR';
    case EMIRADOS_ARABES_UNIDOS = 'ARE';
    case REINO_UNIDO = 'GBR';
    case ESTADOS_UNIDOS = 'USA';
    case URUGUAI = 'URY';
    case UZBEQUISTAO = 'UZB';
    case VANUATU = 'VUT';
    case CIDADE_DO_VATICANO = 'VAT';
    case VENEZUELA = 'VEN';
    case VIETNA = 'VNM';
    case IEMEN = 'YEM';
    case ZAMBIA = 'ZMB';
    case ZIMBABUE = 'ZWE';

    public static function match(string $code): self
    {
        return match ($code) {
            'AFG' => self::AFEGANISTAO,
            'ALB' => self::ALBANIA,
            'DZA' => self::ARGELIA,
            'AND' => self::ANDORRA,
            'AGO' => self::ANGOLA,
            'ATG' => self::ANTIGUA_E_BARBUDA,
            'ARG' => self::ARGENTINA,
            'ARM' => self::ARMENIA,
            'AUS' => self::AUSTRALIA,
            'AUT' => self::AUSTRIA,
            'AZE' => self::AZERBAIJAO,
            'BHS' => self::BAHAMAS,
            'BHR' => self::BAREIN,
            'BGD' => self::BANGLADESH,
            'BRB' => self::BARBADOS,
            'BLR' => self::BELARUS,
            'BEL' => self::BELGICA,
            'BLZ' => self::BELIZE,
            'BEN' => self::BENIM,
            'BTN' => self::BUTAO,
            'BOL' => self::BOLIVIA,
            'BIH' => self::BOSNIA_E_HERZEGOVINA,
            'BWA' => self::BOTSUANA,
            'BRA' => self::BRASIL,
            'BRN' => self::BRUNEI,
            'BGR' => self::BULGARIA,
            'BFA' => self::BURKINA_FASO,
            'BDI' => self::BURUNDI,
            'CPV' => self::CABO_VERDE,
            'KHM' => self::CAMBOJA,
            'CMR' => self::CAMAROES,
            'CAN' => self::CANADA,
            'CAF' => self::REPUBLICA_CENTRO_AFRICANA,
            'TCD' => self::CHADE,
            'CHL' => self::CHILE,
            'CHN' => self::CHINA,
            'COL' => self::COLOMBIA,
            'COM' => self::COMORES,
            'COG' => self::CONGO,
            'CRI' => self::COSTA_RICA,
            'HRV' => self::CROACIA,
            'CUB' => self::CUBA,
            'CYP' => self::CHIPRE,
            'CZE' => self::REPUBLICA_CHECA,
            'DNK' => self::DINAMARCA,
            'DJI' => self::DJIBUTI,
            'DMA' => self::DOMINICA,
            'DOM' => self::REPUBLICA_DOMINICANA,
            'ECU' => self::EQUADOR,
            'EGY' => self::EGITO,
            'SLV' => self::EL_SALVADOR,
            'GNQ' => self::GUINE_EQUATORIAL,
            'ERI' => self::ERITREIA,
            'EST' => self::ESTONIA,
            'SWZ' => self::ESUATINI,
            'ETH' => self::ETIOPIA,
            'FJI' => self::FIJI,
            'FIN' => self::FINLANDIA,
            'FRA' => self::FRANCA,
            'GAB' => self::GABAO,
            'GMB' => self::GAMBIA,
            'GEO' => self::GEORGIA,
            'DEU' => self::ALEMANHA,
            'GHA' => self::GANA,
            'GRC' => self::GRECIA,
            'GRD' => self::GRANADA,
            'GTM' => self::GUATEMALA,
            'GIN' => self::GUINE,
            'GNB' => self::GUINE_BISSAU,
            'GUY' => self::GUIANA,
            'HTI' => self::HAITI,
            'HND' => self::HONDURAS,
            'HUN' => self::HUNGRIA,
            'ISL' => self::ISLANDIA,
            'IND' => self::INDIA,
            'IDN' => self::INDONESIA,
            'IRN' => self::IRA,
            'IRQ' => self::IRAQUE,
            'IRL' => self::IRLANDA,
            'ISR' => self::ISRAEL,
            'ITA' => self::ITALIA,
            'JAM' => self::JAMAICA,
            'JPN' => self::JAPAO,
            'JOR' => self::JORDANIA,
            'KAZ' => self::CASAQUISTAO,
            'KEN' => self::QUENIA,
            'KIR' => self::QUIRIBATI,
            'PRK' => self::COREIA_DO_NORTE,
            'KOR' => self::COREIA_DO_SUL,
            'XKX' => self::KOSOVO,
            'KWT' => self::KUWAIT,
            'KGZ' => self::QUIRGUIZISTAO,
            'LAO' => self::LAOS,
            'LVA' => self::LETONIA,
            'LBN' => self::LIBANO,
            'LSO' => self::LESOTO,
            'LBR' => self::LIBERIA,
            'LBY' => self::LIBIA,
            'LIE' => self::LIECHTENSTEIN,
            'LTU' => self::LITUANIA,
            'LUX' => self::LUXEMBURGO,
            'MDG' => self::MADAGASCAR,
            'MWI' => self::MALAWI,
            'MYS' => self::MALASIA,
            'MDV' => self::MALDIVAS,
            'MLI' => self::MALI,
            'MLT' => self::MALTA,
            'MHL' => self::ILHAS_MARSHALL,
            'MRT' => self::MAURITANIA,
            'MUS' => self::MAURICIO,
            'MEX' => self::MEXICO,
            'FSM' => self::MICRONESIA,
            'MDA' => self::MOLDAVIA,
            'MCO' => self::MONACO,
            'MNG' => self::MONGOLIA,
            'MNE' => self::MONTENEGRO,
            'MAR' => self::MARROCOS,
            'MOZ' => self::MOCAMBIQUE,
            'MMR' => self::MIANMAR,
            'NAM' => self::NAMIBIA,
            'NRU' => self::NAURU,
            'NPL' => self::NEPAL,
            'NLD' => self::PAISES_BAIXOS,
            'NZL' => self::NOVA_ZELANDIA,
            'NIC' => self::NICARAGUA,
            'NER' => self::NIGER,
            'NGA' => self::NIGERIA,
            'MKD' => self::MACEDONIA_DO_NORTE,
            'NOR' => self::NORUEGA,
            'OMN' => self::OMA,
            'PAK' => self::PAQUISTAO,
            'PLW' => self::PALAU,
            'PSE' => self::PALESTINA,
            'PAN' => self::PANAMA,
            'PNG' => self::PAPUA_NOVA_GUINE,
            'PRY' => self::PARAGUAI,
            'PER' => self::PERU,
            'PHL' => self::FILIPINAS,
            'POL' => self::POLONIA,
            'PRT' => self::PORTUGAL,
            'QAT' => self::CATAR,
            'ROU' => self::RUMENIA,
            'RUS' => self::RUSSIA,
            'RWA' => self::RUANDA,
            'KNA' => self::SAO_CRISTOVAO_E_NEVES,
            'LCA' => self::SANTA_LUCIA,
            'VCT' => self::SAO_VICENTE_E_GRANADINAS,
            'WSM' => self::SAMOA,
            'SMR' => self::SAN_MARINO,
            'STP' => self::SAO_TOME_E_PRINCIPE,
            'SAU' => self::ARABIA_SAUDITA,
            'SEN' => self::SENEGAL,
            'SRB' => self::SERVIA,
            'SYC' => self::SEICHELES,
            'SLE' => self::SERRA_LEOA,
            'SGP' => self::CINGAPURA,
            'SVK' => self::ESLOVAQUIA,
            'SVN' => self::ESLOVENIA,
            'SLB' => self::ILHAS_SALOMAO,
            'SOM' => self::SOMALIA,
            'ZAF' => self::AFRICA_DO_SUL,
            'SSD' => self::SUDÃO_DO_SUL,
            'ESP' => self::ESPANHA,
            'LKA' => self::SRI_LANKA,
            'SDN' => self::SUDÃO,
            'SUR' => self::SURINAME,
            'SWE' => self::SUECIA,
            'CHE' => self::SUICA,
            'SYR' => self::SIRIA,
            'TWN' => self::TAIWAN,
            'TJK' => self::TAJIQUISTAO,
            'TZA' => self::TANZANIA,
            'THA' => self::TAILANDIA,
            'TLS' => self::TIMOR_LESTE,
            'TGO' => self::TOGO,
            'TON' => self::TONGA,
            'TTO' => self::TRINDADE_E_TOBAGO,
            'TUN' => self::TUNISIA,
            'TUR' => self::TURQUIA,
            'TKM' => self::TURQUEMENISTAO,
            'TUV' => self::TUVALU,
            'UGA' => self::UGANDA,
            'UKR' => self::UCRANIA,
            'ARE' => self::EMIRADOS_ARABES_UNIDOS,
            'GBR' => self::REINO_UNIDO,
            'USA' => self::ESTADOS_UNIDOS,
            'URY' => self::URUGUAI,
            'UZB' => self::UZBEQUISTAO,
            'VUT' => self::VANUATU,
            'VAT' => self::CIDADE_DO_VATICANO,
            'VEN' => self::VENEZUELA,
            'VNM' => self::VIETNA,
            'YEM' => self::IEMEN,
            'ZMB' => self::ZAMBIA,
            'ZWE' => self::ZIMBABUE,
            default => throw new ValidacaoErrors("País inválido: {$code}")
        };
    }

    public static function paises(): array
    {
        return array_column(self::cases(), 'value');
    }
}
