<?php
namespace MrPrompt\Cielo;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-22 at 09:46:48.
 */
class ClienteTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Cliente
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Cliente;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::__call
     * @todo   Implement test__call().
     */
    public function test__call()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getUrlRetorno
     * @todo   Implement testGetUrlRetorno().
     */
    public function testGetUrlRetorno()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setUrlRetorno
     * @todo   Implement testSetUrlRetorno().
     */
    public function testSetUrlRetorno()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getXml
     * @todo   Implement testGetXml().
     */
    public function testGetXml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setXml
     * @todo   Implement testSetXml().
     */
    public function testSetXml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getIdioma
     * @todo   Implement testGetIdioma().
     */
    public function testGetIdioma()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setIdioma
     * @todo   Implement testSetIdioma().
     */
    public function testSetIdioma()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getAmbiente
     * @todo   Implement testGetAmbiente().
     */
    public function testGetAmbiente()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setAmbiente
     * @todo   Implement testSetAmbiente().
     */
    public function testSetAmbiente()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getSslCertificate
     * @todo   Implement testGetSslCertificate().
     */
    public function testGetSslCertificate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setSslCertificate
     * @todo   Implement testSetSslCertificate().
     */
    public function testSetSslCertificate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::transacao
     * @todo   Implement testTransacao().
     */
    public function testTransacao()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::autorizacao
     * @todo   Implement testAutorizacao().
     */
    public function testAutorizacao()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::captura
     * @todo   Implement testCaptura().
     */
    public function testCaptura()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::cancelamento
     * @todo   Implement testCancelamento().
     */
    public function testCancelamento()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::consulta
     * @todo   Implement testConsulta().
     */
    public function testConsulta()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::tid
     * @todo   Implement testTid().
     */
    public function testTid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::autorizacaoPortador
     * @todo   Implement testAutorizacaoPortador().
     */
    public function testAutorizacaoPortador()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::enviaChamada
     * @todo   Implement testEnviaChamada().
     */
    public function testEnviaChamada()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
