<?php
namespace MrPrompt\Cielo;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-22 at 09:46:48.
 */
class TransacaoTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Transacao
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Transacao;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers MrPrompt\Cielo\Transacao::getTid
     * @todo   Implement testGetTid().
     */
    public function testGetTid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Transacao::setTid
     * @todo   Implement testSetTid().
     */
    public function testSetTid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Transacao::getProduto
     * @todo   Implement testGetProduto().
     */
    public function testGetProduto()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Transacao::setProduto
     * @todo   Implement testSetProduto().
     */
    public function testSetProduto()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Transacao::getParcelas
     * @todo   Implement testGetParcelas().
     */
    public function testGetParcelas()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Transacao::setParcelas
     * @todo   Implement testSetParcelas().
     */
    public function testSetParcelas()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Transacao::getMoeda
     * @todo   Implement testGetMoeda().
     */
    public function testGetMoeda()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Transacao::setMoeda
     * @todo   Implement testSetMoeda().
     */
    public function testSetMoeda()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Transacao::getCapturar
     * @todo   Implement testGetCapturar().
     */
    public function testGetCapturar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Transacao::setCapturar
     * @todo   Implement testSetCapturar().
     */
    public function testSetCapturar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Transacao::getAutorizar
     * @todo   Implement testGetAutorizar().
     */
    public function testGetAutorizar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Transacao::setAutorizar
     * @todo   Implement testSetAutorizar().
     */
    public function testSetAutorizar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Transacao::getDataHora
     * @todo   Implement testGetDataHora().
     */
    public function testGetDataHora()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Transacao::setDataHora
     * @todo   Implement testSetDataHora().
     */
    public function testSetDataHora()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Transacao::getNumero
     * @todo   Implement testGetNumero().
     */
    public function testGetNumero()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Transacao::setNumero
     * @todo   Implement testSetNumero().
     */
    public function testSetNumero()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Transacao::getValor
     * @todo   Implement testGetValor().
     */
    public function testGetValor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Transacao::setValor
     * @todo   Implement testSetValor().
     */
    public function testSetValor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Transacao::setDescricao
     * @todo   Implement testSetDescricao().
     */
    public function testSetDescricao()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Transacao::getDescricao
     * @todo   Implement testGetDescricao().
     */
    public function testGetDescricao()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
