<?php
namespace MrPrompt\Cielo;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-22 at 09:46:48.
 */
class TransacaoTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Transacao
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Transacao;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @test
     * @covers MrPrompt\Cielo\Transacao::getTid
     */
    public function getTid()
    {
        $tid    = uniqid();
        $result = $this->object->setTid($tid);
        
        $this->assertEquals($tid, $this->object->getTid());
    }
    
    /**
     * @test
     * @covers MrPrompt\Cielo\Transacao::setTid
     * @expectedException InvalidArgumentException
     */
    public function setTidDisparaExcessaoQuandoVazio()
    {
        $this->object->setTid('');
    }

    /**
     * @test
     * @covers MrPrompt\Cielo\Transacao::setTid
     */
    public function setTid()
    {
        $tid    = uniqid();
        $result = $this->object->setTid($tid);
        
        $this->assertInstanceOf('MrPrompt\Cielo\Transacao', $result);
    }

    /**
     * @test
     * @covers MrPrompt\Cielo\Transacao::getProduto
     * @todo   Implement testGetProduto().
     */
    public function getProduto()
    {
        
    }

    /**
     * @test
     * @covers MrPrompt\Cielo\Transacao::setProduto
     * @todo   Implement testSetProduto().
     */
    public function setProduto()
    {
        
    }

    /**
     * @test
     * @covers MrPrompt\Cielo\Transacao::getParcelas
     * @todo   Implement testGetParcelas().
     */
    public function getParcelas()
    {
        
    }

    /**
     * @test
     * @covers MrPrompt\Cielo\Transacao::setParcelas
     * @todo   Implement testSetParcelas().
     */
    public function setParcelas()
    {
        
    }

    /**
     * @test
     * @covers MrPrompt\Cielo\Transacao::getMoeda
     * @todo   Implement testGetMoeda().
     */
    public function getMoeda()
    {
        
    }

    /**
     * @test
     * @covers MrPrompt\Cielo\Transacao::setMoeda
     * @todo   Implement testSetMoeda().
     */
    public function setMoeda()
    {
        
    }

    /**
     * @test
     * @covers MrPrompt\Cielo\Transacao::getCapturar
     * @todo   Implement testGetCapturar().
     */
    public function getCapturar()
    {
        
    }

    /**
     * @test
     * @covers MrPrompt\Cielo\Transacao::setCapturar
     * @todo   Implement testSetCapturar().
     */
    public function setCapturar()
    {
        
    }

    /**
     * @test
     * @covers MrPrompt\Cielo\Transacao::getAutorizar
     * @todo   Implement testGetAutorizar().
     */
    public function getAutorizar()
    {
        
    }

    /**
     * @test
     * @covers MrPrompt\Cielo\Transacao::setAutorizar
     * @todo   Implement testSetAutorizar().
     */
    public function setAutorizar()
    {
        
    }

    /**
     * @test
     * @covers MrPrompt\Cielo\Transacao::getDataHora
     * @todo   Implement testGetDataHora().
     */
    public function getDataHora()
    {
        
    }

    /**
     * @test
     * @covers MrPrompt\Cielo\Transacao::setDataHora
     * @todo   Implement testSetDataHora().
     */
    public function setDataHora()
    {
        
    }

    /**
     * @test
     * @covers MrPrompt\Cielo\Transacao::getNumero
     * @todo   Implement testGetNumero().
     */
    public function getNumero()
    {
        
    }

    /**
     * @test
     * @covers MrPrompt\Cielo\Transacao::setNumero
     * @todo   Implement testSetNumero().
     */
    public function setNumero()
    {
        
    }

    /**
     * @test
     * @covers MrPrompt\Cielo\Transacao::getValor
     * @todo   Implement testGetValor().
     */
    public function getValor()
    {
        
    }

    /**
     * @test
     * @covers MrPrompt\Cielo\Transacao::setValor
     * @todo   Implement testSetValor().
     */
    public function setValor()
    {
        
    }

    /**
     * @test
     * @covers MrPrompt\Cielo\Transacao::setDescricao
     * @todo   Implement testSetDescricao().
     */
    public function setDescricao()
    {
        
    }

    /**
     * @test
     * @covers MrPrompt\Cielo\Transacao::getDescricao
     * @todo   Implement testGetDescricao().
     */
    public function getDescricao()
    {
        
    }
}
