<?php
namespace MrPrompt\Cielo;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-22 at 06:24:40.
 */
class ClienteTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Cliente
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Cliente;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::__call
     * @todo   Implement test__call().
     */
    public function test__call()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getUrlRetorno
     * @todo   Implement testGetUrlRetorno().
     */
    public function testGetUrlRetorno()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setUrlRetorno
     * @todo   Implement testSetUrlRetorno().
     */
    public function testSetUrlRetorno()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getTid
     * @todo   Implement testGetTid().
     */
    public function testGetTid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setTid
     * @todo   Implement testSetTid().
     */
    public function testSetTid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getXml
     * @todo   Implement testGetXml().
     */
    public function testGetXml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setXml
     * @todo   Implement testSetXml().
     */
    public function testSetXml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getProduto
     * @todo   Implement testGetProduto().
     */
    public function testGetProduto()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setProduto
     * @todo   Implement testSetProduto().
     */
    public function testSetProduto()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getParcelas
     * @todo   Implement testGetParcelas().
     */
    public function testGetParcelas()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setParcelas
     * @todo   Implement testSetParcelas().
     */
    public function testSetParcelas()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getBandeira
     * @todo   Implement testGetBandeira().
     */
    public function testGetBandeira()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setBandeira
     * @todo   Implement testSetBandeira().
     */
    public function testSetBandeira()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getMoeda
     * @todo   Implement testGetMoeda().
     */
    public function testGetMoeda()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setMoeda
     * @todo   Implement testSetMoeda().
     */
    public function testSetMoeda()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getIdioma
     * @todo   Implement testGetIdioma().
     */
    public function testGetIdioma()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setIdioma
     * @todo   Implement testSetIdioma().
     */
    public function testSetIdioma()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getCapturar
     * @todo   Implement testGetCapturar().
     */
    public function testGetCapturar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setCapturar
     * @todo   Implement testSetCapturar().
     */
    public function testSetCapturar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getAutorizar
     * @todo   Implement testGetAutorizar().
     */
    public function testGetAutorizar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setAutorizar
     * @todo   Implement testSetAutorizar().
     */
    public function testSetAutorizar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getDataHora
     * @todo   Implement testGetDataHora().
     */
    public function testGetDataHora()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setDataHora
     * @todo   Implement testSetDataHora().
     */
    public function testSetDataHora()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getNumero
     * @todo   Implement testGetNumero().
     */
    public function testGetNumero()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setNumero
     * @todo   Implement testSetNumero().
     */
    public function testSetNumero()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getValor
     * @todo   Implement testGetValor().
     */
    public function testGetValor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setValor
     * @todo   Implement testSetValor().
     */
    public function testSetValor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getCartao
     * @todo   Implement testGetCartao().
     */
    public function testGetCartao()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setCartao
     * @todo   Implement testSetCartao().
     */
    public function testSetCartao()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getIndicador
     * @todo   Implement testGetIndicador().
     */
    public function testGetIndicador()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setIndicador
     * @todo   Implement testSetIndicador().
     */
    public function testSetIndicador()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getCodigoSeguranca
     * @todo   Implement testGetCodigoSeguranca().
     */
    public function testGetCodigoSeguranca()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setCodigoSeguranca
     * @todo   Implement testSetCodigoSeguranca().
     */
    public function testSetCodigoSeguranca()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getNomePortador
     * @todo   Implement testGetNomePortador().
     */
    public function testGetNomePortador()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setNomePortador
     * @todo   Implement testSetNomePortador().
     */
    public function testSetNomePortador()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getValidade
     * @todo   Implement testGetValidade().
     */
    public function testGetValidade()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setValidade
     * @todo   Implement testSetValidade().
     */
    public function testSetValidade()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setDescricao
     * @todo   Implement testSetDescricao().
     */
    public function testSetDescricao()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getDescricao
     * @todo   Implement testGetDescricao().
     */
    public function testGetDescricao()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getDebug
     * @todo   Implement testGetDebug().
     */
    public function testGetDebug()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setDebug
     * @todo   Implement testSetDebug().
     */
    public function testSetDebug()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::getAmbiente
     * @todo   Implement testGetAmbiente().
     */
    public function testGetAmbiente()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::setAmbiente
     * @todo   Implement testSetAmbiente().
     */
    public function testSetAmbiente()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::transacao
     * @todo   Implement testTransacao().
     */
    public function testTransacao()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::autorizacao
     * @todo   Implement testAutorizacao().
     */
    public function testAutorizacao()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::captura
     * @todo   Implement testCaptura().
     */
    public function testCaptura()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::cancelamento
     * @todo   Implement testCancelamento().
     */
    public function testCancelamento()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::consulta
     * @todo   Implement testConsulta().
     */
    public function testConsulta()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::tid
     * @todo   Implement testTid().
     */
    public function testTid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MrPrompt\Cielo\Cliente::autorizacaoPortador
     * @todo   Implement testAutorizacaoPortador().
     */
    public function testAutorizacaoPortador()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
